### PR TITLE
Give user options  to choose existed Image and workdir etc..

### PR DESCRIPTION
**Pull request by xZetsubou**
This change will give the user the ability to choose the WORKDIR and whether to download Widnows Image or select exists one.

#2 closes

## Main features
- Choose WORKDIR Directory rather then force user to use c:\
- Choose whether to Download Image or Provide an existed image
- Ability to choose windows edition rather then force win 11 pro.

## info
- There is no need to change download location in the windows download tool 
  This script will modify the config.json of the tool to set new download location in case user wants to download path.

### CODE REVIEW

**Comment by manciuszz** [comment]
It would be nice if we could grant options to select an image. Right now it's hard coded inside 'config.json'. If we fail to find it '$wantedImageIndex' would be null, yet the script would still proceed as everything alright, resulting in a failed build.

**Comment by xZetsubou** [comment]
That's interesting this script only works with Windows 11 Pro editions?

**Comment by manciuszz** [comment]
> That's interesting you mean this script only works with Windows 11 Pro editions?

By default it is looking for an image declared inside the 'config.json' file:
```json
"WantedWindowsEdition": "Windows 11 Pro",
```

If you change it, it will work with other images too. Therefore, we can simply get rid of this and make it as an user option. 
Using this powershell command:
```
Get-WindowsImage -ImagePath ($isoFolder + "sources\install.wim") | ForEach-Object { Write-Host "Found Image: $($_.ImageName)" }
```
We could print all found image names within an .iso. Therefore, we could map each of the items to hotkeys 1,2,3,4,5 etc.

**Comment by xZetsubou** [comment]
> Based on the oscdimg docs, 'bootdata' can't have spaces.

And I guess there is no way to escape spaces, having a spaces in `workDir` I guess shouldn't be allowed.

**Comment by xZetsubou** [comment]
Now probably everything should works fine I hope. [144398a](https://github.com/ianis58/tiny11builder/pull/12/commits/144398a67ed909fd8e0b4be7358539a4f126e24f)
@manciuszz thanks for windows editions checker command. And pointing the issues :) feel free to let me know if there is an issues.

**Comment by manciuszz** [comment]
Here's some thoughts on how to improve the script further:
In my opinion, cases like this ```Write-Output "[1]. Use the default path `n[2]. Change default path`n"``` should be split into two **Write-Output** messages. That would achieve the same thing, but make the code more maintainable and easier to read.

What if the path input is something like "C:\Windows 11 IoT Enterprise x64" (with the quotes) ? 
What if the first path input is an .iso file? Technically, we already got the path to an .iso file then, meaning the Download/Provide ISO step is redundant. 
What if the '.iso' file path is all UPPERCASE (.ISO)? `$isoPath.EndsWith(".iso")` would fail.
The choose available windows edition step should happen before creating any folders and it should contain a '**None**' option to exit intermittently.  In addition, '$wantedImageName' is now being left unused, so the config.json option is redundant. Why not make it look for it and if that fails use the available windows image list as a fallback? Furthermore, you should store `Get-WindowsImage -ImagePath ($isoDriveLetter + ":\sources\install.wim")` inside an object instead of querying it multiple times.

Personally, I don't like this code:
```ps
if ($_confirm_user -like "n" ) {
	clear
	Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
	.\tiny11creator.ps1
}
```
Why not just **return** or **throw** an exception or something ? We can restart the script after it finishes executing and that would give more control to the user. 

Major feature wise, a cool feature to have would be the ability of the script resuming work from last executed step. For example, if we do all the steps until `Write-Output "Building the tiny11.iso file..."` and something happens, like PC crashes/you accidentally close terminal/script fails due to some unforseen issue etc., relaunching the script would resume work from`Write-Output "Building the tiny11.iso file..."` step instead of wasting another 10+ minutes because it deleted all made progress. In short - we need failure management.

**Comment by xZetsubou** [comment]
Would `WorkDir` with quotes even works? I thought it's impossible to escape spaces in `bootdata`.
`WorkDir` choose step will `Directory` it won't accept ISO File.
ISO path is also different from `WorkDir` path it's necessary.

The Major feature you mentioned will require to cache the processes in `log` file. 
What if the user wants to actually stop the process. I would assume when script starts again should make check in log file and ask the user if he wants to continue or start from scratch.

**Comment by manciuszz** [comment]
> Would `WorkDir` with quotes even works? I thought it's impossible to escape spaces in `bootdata`.

Yes. Any path in this script should avoid paths with spaces, because `bootdata` will fail otherwise. Therefore, if the path contains spaces, you should reject it and force the user to input another path, while explaining the reason behind this.

Something like this? https://gist.github.com/manciuszz/1a3ad75dd7f5ef1728426f22993ae2e7

**Comment by xZetsubou** [comment]
I would assume your changes 
> Something like this? https://gist.github.com/manciuszz/1a3ad75dd7f5ef1728426f22993ae2e7

Not based on the latest changes:  https://github.com/ianis58/tiny11builder/pull/12/commits/144398a67ed909fd8e0b4be7358539a4f126e24f and https://github.com/ianis58/tiny11builder/pull/12/commits/64eff1ac92ad4ef2d6a09b6c4d8d646761ab1ef4. Because I changed folder and iso file valid check.
tho your changes / var names makes more sense I would relay on it in and change it modify modify it one more time.

**Comment by manciuszz** [comment]
I checked the code and the entire 'callBack-commonWindowsEdition' function makes no sense to me. Not every .ISO of windows has all those editions. Furthermore, there's like literally 20 or more editions that the list is missing for Windows 11. In addition, your hardcoding support for Windows 11, even though, I believe Windows 10 .ISO's should also work with this script. Not a single step is Windows 11 exclusive as far as I'm aware. 

I assume the entire reason that function exists is for the user to 'swap' windows edition before confirming? Why not just mount the .iso -> fetch the editions -> unmount. Extract this logic into a function and re-use it - the code is already there. This way we get the REAL edition available list.

Anyways...

I had another hot idea that would be interesting to explore - what if the script utilized a RAM disk and did everything there? Curious how much RAM this would need and how much faster everything would happen. Is it even worth it?

**Comment by xZetsubou** [comment]
Choosing an edition before mount made for users who wants to download the image it will take time before it's mount depends on the user internet speed maybe minutes or hours. originally the script made as `one-click` to go so I don't want to go away from that Idea,  `commonEditions` I used the one that includes in the downloaded image . I believe users would most likely will go for changing `workdir` and `download image`.

**Comment by manciuszz** [comment]
Here's another cool idea as a major feature - accepting NTLite configs for even cooler debloating. NTLite config example - https://github.com/ChrisTitusTech/ntlite-configs/blob/main/GamerOS%20Windows%2011.xml

**Pull request closed without merging**
